### ISSUE TITLE
Page 23 won't advance when I do an intuitive thing

### ISSUE THREAD

**Issue by michaelbartnett** [chrisdone/tryhaskell#18]
Hi, I gave this a try after the new haskell.org site was posted with your tutorial embedded in it. I posted this issue to their repo (https://github.com/haskell-infra/hl/issues/7), and @CodeBlock directed me here.

On page 23 it asks:

>Exercise!
>Try to get the 'a' value from this value using pattern matching:
>  
>(10,"abc)

My instinct was to write `let (_,a:_) = (10,"abc")` in a which did give me 'a', but that didn't take.

Mousing over the spoiler revealed `let (_,(a:_)) = (10,"abc") in a` was the necessary incantation. I was left wondering whether the reason was the previous page explained the nested paren syntax, running the tuple and list together is a discouraged style, or something. Hope this is useful to you!

**Comment by igniting** [comment]
`let (_,a:_) = (10,"abc") in a` is a valid answer and it does redirect to the next page.

**Comment by michaelbartnett** [comment]
Interesting. I think last year it wouldn't give `not an expression: `let (_,a:__) = (10,"abc")'` if I omitted the `in a`. Now it does. Maybe I was imagining things. Closing.
