### ISSUE TITLE
Can't run tryhaskell

### ISSUE THREAD

**Issue by bitemyapp** [chrisdone/tryhaskell#21]
```
[callen@delphi ~/code/tryhaskell]$ env PATH=./.cabal-sandbox/bin:$PATH \
  GHC_PACKAGE_PATH=$(cabal sandbox hc-pkg list | grep '^/.*\.cabal-sandbox') \
  TMPDIR=/tmp/tryhaskell ./dist/build/tryhaskell/tryhaskell
ERROR: mueval startup failure:
mueval-core: Time limit exceeded
 ExitFailure 1
```

cabal sandbox add-source'd current version of mueval.

Side note: I had to fix a couple of dependency versions before Cabal could find a solution.

Suggest setting `aeson >= 0.8.0.1` and `bytestring >= 0.10.4.0` to lend Cabal some guidance.

**Comment by bitemyapp** [comment]
>In the end, the problem was simple — tryhaskell was passing -t 1 to mueval, which was not enough time for mueval to do anything interesting.

Good enough for me.

**Comment by a820366174** [comment]
how  to solve  the  issue    'In the end, the problem was simple — tryhaskell was passing -t 1 to mueval, which was not enough time for mueval to do anything interesting.'

**Comment by mietek** [comment]
@a820366174: Pass an appropriate timeout to _mueval_. If you’re trying to run _tryhaskell_, you can set the `MUEVAL_TIMEOUT` environment variable, since https://github.com/mietek/tryhaskell/commit/582fce7ff3c6f537e5bd4ac2b25018941075bb8b.

**Comment by a820366174** [comment]
@bitemyapp   I meet  the same problem with  you ,how did you solve you  problem.  
  mueval -e '1+2'
<no location info>:
    Could not find module âTest.QuickCheckâ
    Use -v to see a list of the files searched for.
@chrisdone

**Comment by a820366174** [comment]
@mietek thank you . I  have another  problem. I  install   all package right.
 but 
  mueval -e '1+2'
:
Could not find module â��Test.QuickCheckâ��
Use -v to see a list of the files searched for.


All the requested packages are already installed

**Comment by mietek** [comment]
@a820366174: _tryhaskell_ still depends on _mueval_ 0.9.1.1, while the first release of _mueval_ that declares the previously-missing dependency on QuickCheck is 0.9.1.1.1. (https://github.com/gwern/mueval/pull/5, https://github.com/gwern/mueval/commit/c41aa40ed63b74c069d1e4e3caa8c8d890cde960) Solution: install the _QuickCheck_ package manually.
