### ISSUE TITLE
getDirectoryContents: Insuffcient hand-holding?

### ISSUE THREAD

**Issue by 8573** [chrisdone/tryhaskell#30]
If I go to <https://try.haskell.org>, click the example expression
`readFile "/welcome"` to insert it into the REPL, and press Enter in
the REPL to run it, I’m told:

> Try playing with this function: getDirectoryContents

If I then do what seems to me to be the obvious thing to do — type
`getDirectoryContents` and press Enter — I get this scary error spew:

    No instance for (Typeable IO)
    arising from a use of ‘show_M649343775715570975412674’
    In the expression:
    show_M649343775715570975412674
    (let e_1 = getDirectoryContents in e_1)
    In an equation for ‘e_164934377571557097541267464934377571557097541267411’:
    e_164934377571557097541267464934377571557097541267411
    = show_M649343775715570975412674
    (let e_1 = getDirectoryContents in e_1)
    In the expression:
    (let
    e_164934377571557097541267464934377571557097541267411
    = show_M649343775715570975412674 (let ... in e_1)
    in e_164934377571557097541267464934377571557097541267411) ::
    String_M649343775715570975412674

Would it not be better to give the learner some more hand-holding
here, perhaps noting that `getDirectoryContents` needs a directory
path as argument?

**Comment by chrisdone** [comment]
This is an incomplete deploy. The proper behaviour is on http://tryhaskell.org/ 

    Type Haskell expressions in here.
    λ getDirectoryContents
    :: FilePath -> IO [FilePath]

@relrod I think this is missing the `pure-io` package, perhaps?
